### ISSUE TITLE
Module not building for 6.15

### ISSUE THREAD

**Issue by amadejkastelic** [berarma/new-lg4ff#126]
The module doesn't seem to build on 6.15. Also, https://github.com/berarma/new-lg4ff/commit/d6c8a82892b2662d017cc301aa94e255d72e9284 - the commit message here or the condition are wrong here, since you're checking if kernel version is <= 6.15, not < 6.15. Changing that doesn't seem to fix it though.

```
       > hid-lg4ff.c:2275:5: error: redefinition of 'lg4ff_init'
       >  2275 | int lg4ff_init(struct hid_device *hid)
       >       |     ^~~~~~~~~~
       > hid-lg4ff.h:19:19: note: previous definition of 'lg4ff_init' with type 'int(struct hid_device *)'
       >    19 | static inline int lg4ff_init(struct hid_device *hdev) { return -1; }
       >       |                   ^~~~~~~~~~
       > hid-lg4ff.c: In function 'lg4ff_init':
       > hid-lg4ff.c:2480:9: error: implicit declaration of function 'hrtimer_init'; did you mean 'hrtimers_init'? [-Wimplicit-function-declaration]
       >  2480 |         hrtimer_init(&entry->hrtimer, CLOCK_MONOTONIC, HRTIMER_MODE_REL);
       >       |         ^~~~~~~~~~~~
       >       |         hrtimers_init
       > hid-lg4ff.c: At top level:
       > hid-lg4ff.c:2498:5: error: redefinition of 'lg4ff_deinit'
       >  2498 | int lg4ff_deinit(struct hid_device *hid)
       >       |     ^~~~~~~~~~~~
       > hid-lg4ff.h:20:19: note: previous definition of 'lg4ff_deinit' with type 'int(struct hid_device *)'
       >    20 | static inline int lg4ff_deinit(struct hid_device *hdev) { return -1; }
       >       |                   ^~~~~~~~~~~~
       > make[4]: *** [/nix/store/gl4zb4minm4ddaz31lhsx2rr964z1gjl-linux-6.15-dev/lib/modules/6.15.0/source/scripts/Makefile.build:203: hid-lg4ff.o] Error 1
       > make[3]: *** [/nix/store/gl4zb4minm4ddaz31lhsx2rr964z1gjl-linux-6.15-dev/lib/modules/6.15.0/source/Makefile:2003: .] Error 2
       > make[2]: *** [/nix/store/gl4zb4minm4ddaz31lhsx2rr964z1gjl-linux-6.15-dev/lib/modules/6.15.0/source/Makefile:248: __sub-make] Error 2
       > make[2]: Leaving directory '/build/source'
       > make[1]: *** [/nix/store/gl4zb4minm4ddaz31lhsx2rr964z1gjl-linux-6.15-dev/lib/modules/6.15.0/source/Makefile:248: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/gl4zb4minm4ddaz31lhsx2rr964z1gjl-linux-6.15-dev/lib/modules/6.15.0/build'
       > make: *** [Makefile:5: default] Error 2
```

**Comment by berarma** [comment]
Yes, it seems I got that check wrong.

And the other error is probably caused because your kernel isn't built with `CONFIG_LOGIWHEELS_FF`.

**Comment by amadejkastelic** [comment]
> Yes, it seems I got that check wrong.

Are you able to open a PR for this?

> And the other error is probably caused because your kernel isn't built with CONFIG_LOGIWHEELS_FF.

Ah, I see. I'll try with `CONFIG_LOGIWHEELS_FF`, thanks.

**Comment by berarma** [comment]
I've fixed the version check in master.
