### ISSUE TITLE
Unable to build on Arch 6.12.1

### ISSUE THREAD

**Issue by notdexterslab** [berarma/new-lg4ff#113]
Kernel: 6.12.1-arch1-1 x86_64 (EndeavourOS)
Wheel: Logitech, Inc. G923 Racing Wheel for PlayStation 4 and PC

All required packages installed, latest `linux-headers` (6.12.1.arch1-1).

Result of running `sudo make` in `/usr/src/new-lg4ff`:
```
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory '/usr/lib/modules/6.12.1-arch1-1/build'
  CC [M]  /usr/src/new-lg4ff/hid-lg.o
/usr/src/new-lg4ff/hid-lg.c:936:25: error: initialization of ‘const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} from incompatible pointer type ‘__u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} [-Wincompatible-pointer-types]
  936 |         .report_fixup = lg_report_fixup,
      |                         ^~~~~~~~~~~~~~~
/usr/src/new-lg4ff/hid-lg.c:936:25: note: (near initialization for ‘lg_driver.report_fixup’)
make[3]: *** [scripts/Makefile.build:229: /usr/src/new-lg4ff/hid-lg.o] Error 1
make[2]: *** [/usr/lib/modules/6.12.1-arch1-1/build/Makefile:1936: /usr/src/new-lg4ff] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.12.1-arch1-1/build'
make: *** [Makefile:5: default] Error 2
```

The driver was working fine for me the other day, but when I run `oversteer`, I get "No device available."

EDIT: When reinstalling `linux-headers`, I get this error:
```
(1/1) Remove upgraded DKMS modules

Error! new-lg4ff/0.3.3.r32.g89d2b09: Missing the module source directory or the symbolic link pointing to it.
Manual intervention is required!

Error! new-lg4ff/0.3.3.r33.g1a2d572: Missing the module source directory or the symbolic link pointing to it.
Manual intervention is required!
```

**Comment by berarma** [comment]
Maybe #112 fixes the issue. You'll need to rebuild the module.

**Comment by notdexterslab** [comment]
It seems part of my issues was a broken symlink in /var/lib/dkms/. I deleted the folder, reinstalled `new-lg4ff`, and now everything's working again!

**Comment by notdexterslab** [comment]
It seems part of my issues was a broken symlink in /var/lib/dkms/. I deleted the folder, reinstalled `new-lg4ff`, and now everything's working again!

**Comment by qreeves** [comment]
I ran into this same problem and the same solution resolved it. 👍
