### ISSUE TITLE
驱动在arm64架构的板子上安装不成功

### ISSUE THREAD

**Issue by yangshaoyun** [berarma/new-lg4ff#122]
你好，我遇到一个报错。我在一块3588的板子上安装驱动时报错，板子是arm64，Ubuntu22.04.4LTS系统。
报错内容是：
ztl@3588:~$ sudo dkms install /usr/src/new-lg4ff-master
Creating symlink /var/lib/dkms/new-lg4ff/0.4.2/source -> /usr/src/new-lg4ff-0.4.2

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.10.198 KVERSION=5.10.198...(bad exit status: 2)
ERROR (dkms apport): binary package for new-lg4ff: 0.4.2 not found
Error! Bad return status for module build on kernel: 5.10.198 (aarch64)
Consult /var/lib/dkms/new-lg4ff/0.4.2/build/make.log for more information.

打开make.log，里面的内容是：
DKMS make.log for new-lg4ff-0.4.2 for kernel 5.10.198 (aarch64)
Wed Mar 19 06:56:51 PM CST 2025
make -C /lib/modules/5.10.198/build M=$PWD
make[1]: 进入目录“/usr/src/linux-headers-5.10.198”
/usr/bin/env: "python": 没有那个文件或目录
  CC [M]  /var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg.o
  CC [M]  /var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.o
/usr/bin/env: "python"/usr/bin/env: "python": 没有那个文件或目录: 没有那个文件或目录

make[2]: *** [scripts/Makefile.build:273：/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.o] 错误 127
make[2]: *** 正在等待未完成的任务....
make[2]: *** [scripts/Makefile.build:273：/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg.o] 错误 127
make[1]: *** [Makefile:1929：/var/lib/dkms/new-lg4ff/0.4.2/build] 错误 2
make[1]: 离开目录“/usr/src/linux-headers-5.10.198”
make: *** [Makefile:5：default] 错误 2

这个问题该怎么解决呢？

**Comment by yangshaoyun** [comment]
**我重新配置了环境变量中的python的路径，还是这个报错：**
ztl@3588:~$ sudo dkms install /usr/src/new-lg4ff-master
Creating symlink /var/lib/dkms/new-lg4ff/0.4.2/source -> /usr/src/new-lg4ff-0.4.2

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.10.198 KVERSION=5.10.198...(bad exit status: 2)
ERROR (dkms apport): binary package for new-lg4ff: 0.4.2 not found
Error! Bad return status for module build on kernel: 5.10.198 (aarch64)
Consult /var/lib/dkms/new-lg4ff/0.4.2/build/make.log for more information.


**打开make.log，里面的错误信息：**
DKMS make.log for new-lg4ff-0.4.2 for kernel 5.10.198 (aarch64)
Thu Mar 20 10:43:54 AM CST 2025
make -C /lib/modules/5.10.198/build M=$PWD
make[1]: 进入目录“/usr/src/linux-headers-5.10.198”
  CC [M]  /var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg.o
  CC [M]  /var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.o
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c:1158:5: error: redefinition of 'lg4ff_adjust_input_event'
 1158 | int lg4ff_adjust_input_event(struct hid_device *hid, struct hid_field *field,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c:22:
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.h:15:19: note: previous definition of 'lg4ff_adjust_input_event' with type 'int(struct hid_device *, struct hid_field *, struct hid_usage *, s32,  struct lg_drv_data *)' {aka 'int(struct hid_device *, struct hid_field *, struct hid_usage *, int,  struct lg_drv_data *)'}
   15 | static inline int lg4ff_adjust_input_event(struct hid_device *hid, struct hid_field *field,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c:1184:5: error: redefinition of 'lg4ff_raw_event'
 1184 | int lg4ff_raw_event(struct hid_device *hdev, struct hid_report *report,
      |     ^~~~~~~~~~~~~~~
In file included from /var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c:22:
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.h:17:19: note: previous definition of 'lg4ff_raw_event' with type 'int(struct hid_device *, struct hid_report *, u8 *, int,  struct lg_drv_data *)' {aka 'int(struct hid_device *, struct hid_report *, unsigned char *, int,  struct lg_drv_data *)'}
   17 | static inline int lg4ff_raw_event(struct hid_device *hdev, struct hid_report *report,
      |                   ^~~~~~~~~~~~~~~
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c: In function 'lg4ff_alternate_modes_store':
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c:1702:67: error: 'lg4ff_no_autoswitch' undeclared (first use in this function)
 1702 |         if (target_product_id == USB_DEVICE_ID_LOGITECH_WHEEL && !lg4ff_no_autoswitch) {
      |                                                                   ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c:1702:67: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c: In function 'lg4ff_handle_multimode_wheel':
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c:2227:14: error: 'lg4ff_no_autoswitch' undeclared (first use in this function)
 2227 |             !lg4ff_no_autoswitch) {
      |              ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c: At top level:
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c:2276:5: error: redefinition of 'lg4ff_init'
 2276 | int lg4ff_init(struct hid_device *hid)
      |     ^~~~~~~~~~
In file included from /var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c:22:
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.h:19:19: note: previous definition of 'lg4ff_init' with type 'int(struct hid_device *)'
   19 | static inline int lg4ff_init(struct hid_device *hdev) { return -1; }
      |                   ^~~~~~~~~~
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c:2495:5: error: redefinition of 'lg4ff_deinit'
 2495 | int lg4ff_deinit(struct hid_device *hid)
      |     ^~~~~~~~~~~~
In file included from /var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.c:22:
/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.h:20:19: note: previous definition of 'lg4ff_deinit' with type 'int(struct hid_device *)'
   20 | static inline int lg4ff_deinit(struct hid_device *hdev) { return -1; }
      |                   ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:273：/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg4ff.o] 错误 1
make[2]: *** 正在等待未完成的任务....
/bin/sh: 1: scripts/basic/fixdep: Exec format error
make[2]: *** [scripts/Makefile.build:273：/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg.o] 错误 126
make[2]: *** 正在删除文件“/var/lib/dkms/new-lg4ff/0.4.2/build/hid-lg.o”
make[1]: *** [Makefile:1929：/var/lib/dkms/new-lg4ff/0.4.2/build] 错误 2
make[1]: 离开目录“/usr/src/linux-headers-5.10.198”
make: *** [Makefile:5：default] 错误 2
